### ISSUE TITLE
google colab error  

### ISSUE THREAD

**Issue by diegoegus1** [nousr/koi#17]
RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error (look up to see its traceback):
module 'PIL.Image' has no attribute 'Resampling'

**Comment by nousr** [comment]
Hey! this happens when you don't restart the notebook before continuing on with the rest of the setup process! We added a disclaimer in a more recent version of the notebook to remind you to do this 🙂

if you did that and are still running into the issue, could you please re-open this issue with a copy of the "!pip list" so that we can diagnose this issue further ? 

thanks!
